### ISSUE TITLE
Fakturagrunnlag bruker gammel excel-klasse

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMsms#13]
Funksjonen funker ikke da den bruker en gammel excel-klasse som ikke støtter php7.2. Vi har innført arvtakeren phpspreadsheets, men ikke oppdatert koden.

**OBS:** 
Etter denne er løst, kan #6 spesifiseres.

**Comment by mariusmandal** [comment]
Flyttet til feature request system

**Comment by mariusmandal** [comment]
Tatt inn i [Sprint#3](https://github.com/orgs/UKMNorge/projects/28)

**Comment by mariusmandal** [comment]
## Gjenskape problemet

- Logg inn
- Velg "fakturering" under "sms" i menyen (UKM Norge-admin)

**Comment by mariusmandal** [comment]
## Løsningsforslag

**Beregnet tid: 4t**

Koden bruker i dag "PHPExcel", som ikke lenger virker. Skriv om koden til å bruke [UKMNorge\File\Excel](https://github.com/UKMNorge/UKMapi/blob/master/File/Excel.php)

**OBS:** Vi skal bort fra filen `excel.inc.php`. Faktura-problemet utgjør 2 av 4 referanser vi har til filen, så pass på at du fjerner require_once av den filen når du er i gang.

Rapport-modulen bruker denne i dag, hvis du trenger inspirasjon 😊

**Comment by mariusmandal** [comment]
Test i produksjon feilet @slogan-15:

```
Fatal error: 
Uncaught Error: Call to undefined function exCell() in /UKMsms/controller/faktura.controller.php:95 

Stack trace: 
#0 UKMsms/sms.php(62): require_once() 
#1 wp-includes/class-wp-hook.php(292): UKMMsmsfaktura('') 
#2 wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array) 
#3 wp-includes/plugin.php(484): WP_Hook->do_action(Array) 
#4 wp-admin/admin.php(259): do_action('sms_page_UKMMsm...') 
#5 wp-admin/network/admin.php(13): require_once('/home/ukmno/pub...') 
#6 {main} thrown in UKMsms/controller/faktura.controller.php on line 95
```

**Comment by mariusmandal** [comment]
Fortsatt feil @slogan-15 :( 

```
Fatal error: Uncaught Error: Call to a member function cell() on null in UKMsms/controller/faktura.controller.php:95 

Stack trace: 
#0 UKMsms/sms.php(62): require_once() 
#1 wp-includes/class-wp-hook.php(292): UKMMsmsfaktura('') 
#2 wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array) 
#3 wp-includes/plugin.php(484): WP_Hook->do_action(Array) 
#4 wp-admin/admin.php(259): do_action('sms_page_UKMMsm...') 
#5 wp-admin/network/admin.php(13): require_once('/home/ukmno/pub...') 
#6 {main} thrown in UKMsms/controller/faktura.controller.php on line 95
```
