### ISSUE TITLE
Logg funker ikke pga gammel klasse

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMsms#14]
```
Fatal error: Uncaught Exception: 
MONSTRING_V2: _load_by_row krever dataarray! in /etc/php-includes/UKM/Arrangement/Arrangement.php:163 Stack trace: 
#0 /etc/php-includes/UKM/Arrangement/Arrangement.php(157): UKMNorge\Arrangement\Arrangement->_load_by_row(NULL) 
#1 /etc/php-includes/UKM/Arrangement/Arrangement.php(139): UKMNorge\Arrangement\Arrangement->_load_by_id(0) 
#2 /home/ukmno/public_html/wp-content/plugins/UKMsms/ajax.sms.php(22): UKMNorge\Arrangement\Arrangement->__construct(0) 
#3 /home/ukmno/public_html/wp-content/plugins/UKMsms/ajax.sms.php(10): UKMSMS_ajax_log() 
#4 /home/ukmno/public_html/wp-includes/class-wp-hook.php(287): UKMSMS_ajax('') 
#5 /home/ukmno/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) 
#6 /home/ukmno/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
#7 /home/ukmno/public_html/wp-admin/admin-ajax.php(176): do_action('wp_ajax_UKMSMS_...') 
#8 {main} thrown in /etc/php-includes/UKM/Arrangement/Arrangement.php on line 163
```

Usikker på hvorvidt dette gjelder alle eller noen utvalgte

**Comment by mariusmandal** [comment]
Testet Ok i Grimstad, mens feilen oppstår fra UKM Norge-admin

**Comment by mariusmandal** [comment]
## Gjenskape problemet

- Logg inn som UKM Norge
- Velg "SMS" i menyen (fra UKM Norge-adminsiden)
- Trykk "se sms-logg" (liten skrift, rett under overskriften)

**Comment by mariusmandal** [comment]
## Løsningsforslag

**Estimert tid: 3t**

Fjern valget for å vise logg hvis vi er i UKM Norge-admin (tror vi kan bruke `is_network_admin()`)
